export const REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR';
export const SEND_TENANT_REQUEST = 'SEND_TENANT_REQUEST';
export const LOAD_TENANTS_SUCCESS = 'LOAD_TENANTS_SUCCESS';
export const CREATE_TENANT_SUCCESS = 'CREATE_TENANT_SUCCESS';
export const READ_TENANT_SUCCESS = 'READ_TENANT_SUCCESS';
export const UPDATE_TENANT_SUCCESS = 'UPDATE_TENANT_SUCCESS';
export const DELETE_TENANT_SUCCESS = 'DELETE_TENANT_SUCCESS';

export const TURN_ON_FILTER = 'TURN_ON_FILTER';
export const TURN_OFF_FILTER = 'TURN_OFF_FILTER';
