export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const ADD_SUCCESS_NOTIFICATION = 'ADD_SUCCESS_NOTIFICATION';
export const ADD_ERROR_NOTIFICATION = 'ADD_ERROR_NOTIFICATION';

export const RESET_MESSAGE = 'RESET_MESSAGE';
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';

export const REST_REQUST_SUCCESS = 'REST_REQUST_SUCCESS';
export const REST_REQUST_ERROR = 'REST_REQUST_ERROR';
