export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const ADD_SUCCESS_NOTIFICATION = 'ADD_SUCCESS_NOTIFICATION';
export const ADD_ERROR_NOTIFICATION = 'ADD_ERROR_NOTIFICATION';

export const RESET_MESSAGE = 'RESET_MESSAGE';
export const ADD_SUCCESS_MESSAGE = 'ADD_SUCCESS_MESSAGE';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
