FROM node:10.0.0

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# RUN npm rebuild

# Bundle app source
COPY . /usr/src/app

EXPOSE 5000
CMD npm run dev
