export const SEND_EMPLOYEE_REQUEST = 'SEND_EMPLOYEE_REQUEST';
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const READ_EMPLOYEE_SUCCESS = 'READ_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';

export const TURN_ON_FILTER = 'TURN_ON_FILTER';
export const TURN_OFF_FILTER = 'TURN_OFF_FILTER';
