export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
